//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_Dapper2.CRUDService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contato", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ContatoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneFixoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefoneCelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImagemUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ContatoID {
            get {
                return this.ContatoIDField;
            }
            set {
                if ((this.ContatoIDField.Equals(value) != true)) {
                    this.ContatoIDField = value;
                    this.RaisePropertyChanged("ContatoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TelefoneFixo {
            get {
                return this.TelefoneFixoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneFixoField, value) != true)) {
                    this.TelefoneFixoField = value;
                    this.RaisePropertyChanged("TelefoneFixo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TelefoneCelular {
            get {
                return this.TelefoneCelularField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefoneCelularField, value) != true)) {
                    this.TelefoneCelularField = value;
                    this.RaisePropertyChanged("TelefoneCelular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ImagemUrl {
            get {
                return this.ImagemUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImagemUrlField, value) != true)) {
                    this.ImagemUrlField = value;
                    this.RaisePropertyChanged("ImagemUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRUDService.ContatoServiceSoap")]
    public interface ContatoServiceSoap {
        
        // CODEGEN: Generating message contract since element name obj from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inserir", ReplyAction="*")]
        CRUD_Dapper2.CRUDService.InserirResponse Inserir(CRUD_Dapper2.CRUDService.InserirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Inserir", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.InserirResponse> InserirAsync(CRUD_Dapper2.CRUDService.InserirRequest request);
        
        // CODEGEN: Generating message contract since element name obj from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        CRUD_Dapper2.CRUDService.UpdateResponse Update(CRUD_Dapper2.CRUDService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.UpdateResponse> UpdateAsync(CRUD_Dapper2.CRUDService.UpdateRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        CRUD_Dapper2.CRUDService.GetAllResponse GetAll(CRUD_Dapper2.CRUDService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.GetAllResponse> GetAllAsync(CRUD_Dapper2.CRUDService.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        bool Delete(int contaID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int contaID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Inserir", Namespace="http://tempuri.org/", Order=0)]
        public CRUD_Dapper2.CRUDService.InserirRequestBody Body;
        
        public InserirRequest() {
        }
        
        public InserirRequest(CRUD_Dapper2.CRUDService.InserirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRUD_Dapper2.CRUDService.Contato obj;
        
        public InserirRequestBody() {
        }
        
        public InserirRequestBody(CRUD_Dapper2.CRUDService.Contato obj) {
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InserirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InserirResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUD_Dapper2.CRUDService.InserirResponseBody Body;
        
        public InserirResponse() {
        }
        
        public InserirResponse(CRUD_Dapper2.CRUDService.InserirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InserirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int InserirResult;
        
        public InserirResponseBody() {
        }
        
        public InserirResponseBody(int InserirResult) {
            this.InserirResult = InserirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public CRUD_Dapper2.CRUDService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(CRUD_Dapper2.CRUDService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRUD_Dapper2.CRUDService.Contato obj;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(CRUD_Dapper2.CRUDService.Contato obj) {
            this.obj = obj;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUD_Dapper2.CRUDService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(CRUD_Dapper2.CRUDService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(bool UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public CRUD_Dapper2.CRUDService.GetAllRequestBody Body;
        
        public GetAllRequest() {
        }
        
        public GetAllRequest(CRUD_Dapper2.CRUDService.GetAllRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody {
        
        public GetAllRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRUD_Dapper2.CRUDService.GetAllResponseBody Body;
        
        public GetAllResponse() {
        }
        
        public GetAllResponse(CRUD_Dapper2.CRUDService.GetAllResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRUD_Dapper2.CRUDService.Contato[] GetAllResult;
        
        public GetAllResponseBody() {
        }
        
        public GetAllResponseBody(CRUD_Dapper2.CRUDService.Contato[] GetAllResult) {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContatoServiceSoapChannel : CRUD_Dapper2.CRUDService.ContatoServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContatoServiceSoapClient : System.ServiceModel.ClientBase<CRUD_Dapper2.CRUDService.ContatoServiceSoap>, CRUD_Dapper2.CRUDService.ContatoServiceSoap {
        
        public ContatoServiceSoapClient() {
        }
        
        public ContatoServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContatoServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContatoServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContatoServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUD_Dapper2.CRUDService.InserirResponse CRUD_Dapper2.CRUDService.ContatoServiceSoap.Inserir(CRUD_Dapper2.CRUDService.InserirRequest request) {
            return base.Channel.Inserir(request);
        }
        
        public int Inserir(CRUD_Dapper2.CRUDService.Contato obj) {
            CRUD_Dapper2.CRUDService.InserirRequest inValue = new CRUD_Dapper2.CRUDService.InserirRequest();
            inValue.Body = new CRUD_Dapper2.CRUDService.InserirRequestBody();
            inValue.Body.obj = obj;
            CRUD_Dapper2.CRUDService.InserirResponse retVal = ((CRUD_Dapper2.CRUDService.ContatoServiceSoap)(this)).Inserir(inValue);
            return retVal.Body.InserirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.InserirResponse> CRUD_Dapper2.CRUDService.ContatoServiceSoap.InserirAsync(CRUD_Dapper2.CRUDService.InserirRequest request) {
            return base.Channel.InserirAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.InserirResponse> InserirAsync(CRUD_Dapper2.CRUDService.Contato obj) {
            CRUD_Dapper2.CRUDService.InserirRequest inValue = new CRUD_Dapper2.CRUDService.InserirRequest();
            inValue.Body = new CRUD_Dapper2.CRUDService.InserirRequestBody();
            inValue.Body.obj = obj;
            return ((CRUD_Dapper2.CRUDService.ContatoServiceSoap)(this)).InserirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUD_Dapper2.CRUDService.UpdateResponse CRUD_Dapper2.CRUDService.ContatoServiceSoap.Update(CRUD_Dapper2.CRUDService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public bool Update(CRUD_Dapper2.CRUDService.Contato obj) {
            CRUD_Dapper2.CRUDService.UpdateRequest inValue = new CRUD_Dapper2.CRUDService.UpdateRequest();
            inValue.Body = new CRUD_Dapper2.CRUDService.UpdateRequestBody();
            inValue.Body.obj = obj;
            CRUD_Dapper2.CRUDService.UpdateResponse retVal = ((CRUD_Dapper2.CRUDService.ContatoServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.UpdateResponse> CRUD_Dapper2.CRUDService.ContatoServiceSoap.UpdateAsync(CRUD_Dapper2.CRUDService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.UpdateResponse> UpdateAsync(CRUD_Dapper2.CRUDService.Contato obj) {
            CRUD_Dapper2.CRUDService.UpdateRequest inValue = new CRUD_Dapper2.CRUDService.UpdateRequest();
            inValue.Body = new CRUD_Dapper2.CRUDService.UpdateRequestBody();
            inValue.Body.obj = obj;
            return ((CRUD_Dapper2.CRUDService.ContatoServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRUD_Dapper2.CRUDService.GetAllResponse CRUD_Dapper2.CRUDService.ContatoServiceSoap.GetAll(CRUD_Dapper2.CRUDService.GetAllRequest request) {
            return base.Channel.GetAll(request);
        }
        
        public CRUD_Dapper2.CRUDService.Contato[] GetAll() {
            CRUD_Dapper2.CRUDService.GetAllRequest inValue = new CRUD_Dapper2.CRUDService.GetAllRequest();
            inValue.Body = new CRUD_Dapper2.CRUDService.GetAllRequestBody();
            CRUD_Dapper2.CRUDService.GetAllResponse retVal = ((CRUD_Dapper2.CRUDService.ContatoServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.GetAllResponse> CRUD_Dapper2.CRUDService.ContatoServiceSoap.GetAllAsync(CRUD_Dapper2.CRUDService.GetAllRequest request) {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<CRUD_Dapper2.CRUDService.GetAllResponse> GetAllAsync() {
            CRUD_Dapper2.CRUDService.GetAllRequest inValue = new CRUD_Dapper2.CRUDService.GetAllRequest();
            inValue.Body = new CRUD_Dapper2.CRUDService.GetAllRequestBody();
            return ((CRUD_Dapper2.CRUDService.ContatoServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        public bool Delete(int contaID) {
            return base.Channel.Delete(contaID);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int contaID) {
            return base.Channel.DeleteAsync(contaID);
        }
    }
}
